package com.enm.costcalculrator.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "MemberTransportCost")
public class MemberTransportCost {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String memberId;
    @DynamoDBAttribute
    private Integer opportunityCost;
    @DynamoDBAttribute
    private Integer car;
    @DynamoDBAttribute
    private Integer walking;
    @DynamoDBAttribute
    private Integer bus;
    @DynamoDBAttribute
    private Integer subway;

}
